<a href="https://colab.research.google.com/github/satyam1354/Tensorflow/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.5.1+cu124


In [3]:
if torch.cuda.is_available():
  print("GPU is available!!!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU only")

GPU is available!!!
Using GPU: Tesla T4


# **creating A tensors**

In [4]:
#using empty -> pre memory values
torch.empty(2,3)

tensor([[1.0027e-10, 4.4275e-41, 1.0027e-10],
        [4.4275e-41, 0.0000e+00, 0.0000e+00]])

In [5]:
# check type
a = torch.empty(2,3)
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(3,3)

tensor([[0.5913, 0.3591, 0.2438],
        [0.5678, 0.5038, 0.0037],
        [0.1902, 0.2108, 0.4495]])

In [9]:
# use of seed  -> each time rand gives random values
torch.rand(2,3)

tensor([[0.7401, 0.5553, 0.5220],
        [0.6726, 0.6889, 0.1305]])

In [10]:
# manual seed   -> random values does not changes with  seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

#arange
print("usinga arange ->", torch.arange(0, 10, 2))
# using linespace -> linear space
print("using linspace ->", torch.linspace(0, 10, 10))
#using eye ->identity matrix (diagonal matrix)
print("using eye ->", torch.eye(5))
#using full
print("usign full ->", torch.full((3,3),5))

usinga arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
usign full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor **Shapes**

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)  # shape copy of x

tensor([[135704572886416,       134492784,       134287712],
        [              0,               0,       134493088]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# **Tensor Data Types**

In [18]:
# find data types
x.dtype

torch.int64

In [19]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# **1 Mathematical Operations**

In [22]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [23]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 4
# division
x / 3
# integer division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x ** 2

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])
tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])


tensor([[0.1048, 0.7565],
        [0.2239, 0.3023]])

# **2 Element wise operation**

In [31]:
## similarly we can when we have two numbers also
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)
# adding , subtracting item wise
a + b
a - b
a * b
a / b
a ** b
a % b

tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])
tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])


tensor([[0.2015, 0.2475],
        [0.2168, 0.2420]])

In [24]:
c = torch.tensor([2,-3,4,-5])
c

tensor([ 2, -3,  4, -5])

In [25]:
# abs ==all +ve
torch.abs(c)

tensor([2, 3, 4, 5])

In [26]:
# negative ==  reverse no
torch.neg(c)

tensor([-2,  3, -4,  5])

In [27]:
d = torch.tensor([1.9,3.333,4.3,-5.99])
# round
torch.round(d)

tensor([ 2.,  3.,  4., -6.])

In [28]:
#ceil
torch.ceil(d)

tensor([ 2.,  4.,  5., -5.])

In [29]:
# floor
torch.floor(d)

tensor([ 1.,  3.,  4., -6.])

In [30]:
# clamp  == to keeping the value bw min and max  range
torch.clamp(d, min=2, max = 3)

tensor([2., 3., 3., 2.])

# **3 Reducti0n Operation**

In [43]:
e = torch.randint(size=(2,3), low = 0, high = 10, dtype = torch.float32)
e

tensor([[9., 7., 5.],
        [9., 8., 9.]])

In [37]:
# sum
torch.sum(e)
# sum along columnns
torch.sum(e, dim = 0)
# sum along rows
torch.sum(e, dim = 1)

tensor([14, 19])

In [48]:
# mean when (dtype = torch.float32)
torch.mean(e)
# mean along columns
torch.mean(e, dim = 0)
# mean along rows
torch.mean(e, dim = 1)

tensor([7.0000, 8.6667])

In [45]:
# median
torch.median(e)

tensor(8.)

In [50]:
# max and min
torch.max(e)
torch.min(e)

tensor(5.)

In [52]:
# product
torch.prod(e)

tensor(204120.)

In [53]:
# standard deviation
torch.std(e)

tensor(1.6021)

In [54]:
# variance
torch.var(e)

tensor(2.5667)

In [56]:
# argmax
torch.argmax(e)
# argmin
torch.argmin(e)

tensor(2)

# **4 Matrix Multipliation**

In [59]:
f = torch.randint(size=(2,3), low = 0, high = 10)
g = torch.randint(size=(3,2), low = 0, high = 10)
print(f)
print(g)

tensor([[3, 5, 0],
        [6, 4, 0]])
tensor([[8, 4],
        [7, 2],
        [3, 8]])


In [60]:
# matrix multiplication
torch.matmul(f, g)

tensor([[59, 22],
        [76, 32]])

In [62]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1, vector2)

tensor(11)

In [63]:
# trnaspose  ->from which dimension to which dimension
torch.transpose(f, 0, 1)

tensor([[3, 6],
        [5, 4],
        [0, 0]])

In [77]:
h = torch.randint(size = (3, 3), low =0, high = 10, dtype = torch.float32)
h


tensor([[1., 0., 5.],
        [1., 0., 0.],
        [2., 2., 3.]])

In [74]:
# determinant  ->having only square matrix
torch.det(h)

tensor(-204.0000)

In [78]:
# inverse
torch.inverse(h)

tensor([[ 0.0000,  1.0000,  0.0000],
        [-0.3000, -0.7000,  0.5000],
        [ 0.2000, -0.2000,  0.0000]])

# **5 Comparison Operator**

In [79]:
i = torch.randint(size = (2,  3), low = 0, high = 10)
j = torch.randint(size = (2,3), low = 0, high = 10)
print(i)
print(j)

tensor([[7, 1, 5],
        [0, 2, 3]])
tensor([[7, 0, 2],
        [5, 2, 8]])


In [85]:
# greater thann
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[ True, False, False],
        [ True,  True,  True]])

# **6 Special Functions**

In [97]:
k = torch.randint(size = (2, 3), low = 0, high = 10, dtype = torch.float32)
k

tensor([[9., 3., 9.],
        [7., 7., 5.]])

In [89]:
# log
torch.log(k)

tensor([[2.0794, 0.0000, 0.6931],
        [1.0986, 0.6931, 1.9459]])

In [92]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 2.7183e+00, 7.3891e+00],
        [2.0086e+01, 7.3891e+00, 1.0966e+03]])

In [93]:
# sqrt
torch.sqrt(k)

tensor([[2.8284, 1.0000, 1.4142],
        [1.7321, 1.4142, 2.6458]])

In [94]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.7311, 0.8808],
        [0.9526, 0.8808, 0.9991]])

In [98]:
# softmax   -> expects float type data
torch.softmax(k , dim= 0)

tensor([[0.8808, 0.0180, 0.9820],
        [0.1192, 0.9820, 0.0180]])

In [99]:
# relu
torch.relu(k)

tensor([[9., 3., 9.],
        [7., 7., 5.]])

# **Implace Operations  ( _ )**

In [100]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)
print(m)
print(n)

tensor([[0.9991, 0.1133, 0.0135],
        [0.1450, 0.7819, 0.3134]])
tensor([[0.2983, 0.3436, 0.2028],
        [0.9792, 0.4947, 0.3617]])


In [102]:
# m + n ->takes new place
m.add_(n)

tensor([[1.2974, 0.4569, 0.2163],
        [1.1242, 1.2766, 0.6751]])

In [104]:
# torch.relu(m) -> creates new tensor and save value in it
m.relu_()  # -> performs operation in this tensor  ->just by placing _ after operation

tensor([[1.2974, 0.4569, 0.2163],
        [1.1242, 1.2766, 0.6751]])

# **Copying  a Tensor**

In [110]:
a = torch.rand(2, 3)
a

tensor([[0.1637, 0.0899, 0.3139],
        [0.1219, 0.3516, 0.2316]])

In [111]:
b = a  # -> any changes in a also changes b
b


tensor([[0.1637, 0.0899, 0.3139],
        [0.1219, 0.3516, 0.2316]])

In [116]:
print(id(a))  #  both have same id
print(id(b))

135700261967376
135700261967376


In [119]:
b = a.clone()
print(b)
print(id(a))
print(id(b))

tensor([[0.1637, 0.0899, 0.3139],
        [0.1219, 0.3516, 0.2316]])
135700261967376
135704273728144


# ***Tensor Operations on GPU***

In [4]:
torch.cuda.is_available()

True

In [5]:
device = torch.device('cuda')
device

device(type='cuda')

In [6]:
# creating a new tensor on GPU
torch.rand((2, 3), device = device)

tensor([[0.2034, 0.9441, 0.6791],
        [0.7952, 0.6241, 0.4805]], device='cuda:0')

In [8]:
# moving an existing tensor on GPU
a = torch.rand((2,3))
print(a)
print()
b = a.to(device)
print(b)
print()
print(b + 5)

tensor([[0.5808, 0.9677, 0.8902],
        [0.8705, 0.5952, 0.6698]])

tensor([[0.5808, 0.9677, 0.8902],
        [0.8705, 0.5952, 0.6698]], device='cuda:0')

tensor([[5.5808, 5.9677, 5.8902],
        [5.8705, 5.5952, 5.6698]], device='cuda:0')


In [13]:
import torch
import time

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 =  torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on cpu
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices on GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on gpu
gpu_time = time.time()

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 24.0993 seconds
Time on GPU: 1739987591.3012 seconds

Speedup (CPU time / GPU time): 1.3850284150260997e-08


# **Reshaping Tensors**

In [14]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
# reshape
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [17]:
# flatten  # in 1-D
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.3508, 0.4386, 0.8819, 0.8640],
         [0.3755, 0.6903, 0.8789, 0.0251],
         [0.8126, 0.3065, 0.7154, 0.0710]],

        [[0.4879, 0.9678, 0.8946, 0.9249],
         [0.7020, 0.1398, 0.6034, 0.6109],
         [0.4319, 0.0697, 0.6164, 0.7793]]])

In [20]:
# permute  # changing sha
b.permute(2, 1, 0).shape
b.permute(2, 1, 0)

tensor([[[0.3508, 0.4879],
         [0.3755, 0.7020],
         [0.8126, 0.4319]],

        [[0.4386, 0.9678],
         [0.6903, 0.1398],
         [0.3065, 0.0697]],

        [[0.8819, 0.8946],
         [0.8789, 0.6034],
         [0.7154, 0.6164]],

        [[0.8640, 0.9249],
         [0.0251, 0.6109],
         [0.0710, 0.7793]]])

In [24]:
# unsqueeze  ## adding a new dimesion
# image size
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [27]:
# squeeze
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

# **NumPy and PyTorch**

In [28]:
import numpy as np
# moving of tensors bw numpy and pytorch

In [38]:
a = torch.tensor([1, 2, 3])
print(a)
print(type(a))

tensor([1, 2, 3])
<class 'torch.Tensor'>


In [37]:
b = a.numpy()
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [39]:
c = np.array([1, 2, 3])
print(c)
print(type(c))

[1 2 3]
<class 'numpy.ndarray'>


In [43]:
to = torch.from_numpy(c)
print(to)
print(type(to))

tensor([1, 2, 3])
<class 'torch.Tensor'>
