<a href="https://colab.research.google.com/github/satyam1354/Tensorflow/blob/main/Numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# speed taste
from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)
A = list(a)
B = list(b)
T = 1000
def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i]*B[i]
    return dot
def dot2():
    return np.dot(a,b)
start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end-start

start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end-start
print('list calculation = ', t1)
print('np.dot = ',t2)
print('ratio = ',t1/t2)






list calculation =  0.16332450500001983
np.dot =  0.0013996330000054513
ratio =  116.69095041298948


In [ ]:

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
a=np.array(list1)
b=np.array(list2)
list1 = list1 + [9]
# list1 = list1 * 2
# print(dot3)

In [ ]:
a=a + np.array([9])
a=a*2
s =np.sqrt(a)
l =np.log(a)
sum = a @ b
dot = np.dot(a,b)
sum1 = a + b
sum2 = a * b
dot2 = np.sum(sum2)
dot3 = (a*b).sum()
print(list1)
print(a)
print(s)
print(l)
print(sum1)
print(sum2)
print(sum)
print(dot)
print(dot2)

[1, 2, 3, 4, 5, 9]
[20 22 24 26 28]
[4.47213595 4.69041576 4.89897949 5.09901951 5.29150262]
[2.99573227 3.09104245 3.17805383 3.25809654 3.33220451]
[26 29 32 35 38]
[120 154 192 234 280]
980
980
980


In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)
print(a[0,0])
print(a[:,0])   #  :=> column
print(a[0,:])
print(np.linalg.inv(a))
print(np.linalg.det(a)) #determinant
c = np.diag(a)
print(np.diag(a))   #diagonal
print(np.diag(c))   #diagonal array


[[1 2]
 [3 4]]
(2, 2)
1
[1 3]
[1 2]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[1 4]
[[1 0]
 [0 4]]


In [ ]:

a = np.array([10,20,35,40,55,60,70])
b = [1,3,5]
print(a[b])  #print b index element
even =np.argwhere(a%2==0).flatten()
print(a[even])


[20 40 60]
[10 20 40 60 70]


In [ ]:
a = np.arange(1,7)
print(a)
print(a.shape)
b = a.reshape((2,3))
b = a[np.newaxis , :]
b = a[: , np.newaxis]
print(b.shape)
print(b)

[1 2 3 4 5 6]
(6,)
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
